CombatDuration:
  Entity: 10
  Player: 15
  # Duration of the combat timer. Separate for entities and players. Type an integer.

WorldName: "Open_World"
# Name of the world that will be affected. Type a string.

Permission:
  Remove:
    - "essentials.tpa"
    - "essentials.back"
# Permissions that will be removed when the player enters combat. Type an array of strings. Replace with [] if
# if you are not using any permissions.
